### ISSUE TITLE
CreateLogStream access denied

### ISSUE THREAD

**Issue by p-doyle** [awslabs/aws-crr-monitor#8]
After setting up the stack I received some errors in cloudtrail:

`arn:aws:sts::accountid:assumed-role/CrossRegionReplicationMonitor-CRRHourlyMaintRole-1RCO7JQNPCT8P/CRRHourlyMaint is not authorized to perform: logs:CreateLogStream on resource: arn:aws:logs:us-east-1:accountid:log-group:/aws/lambda/CRRHourlyMaint:log-stream:2019/12/16/[$LATEST]9f7bba28c89742bb8199a28885b893ea`

The policy for the CRRHourlyMaintRole does not include the logs:CreateLogStream action but should it?  Or am I possibly doing something wrong?

**Comment by aijunpeng** [comment]
Thanks for reporting this issue. There seem to be some missing logging permissions. We have added this issue to our solution backlog items and it will be considered in future solution releases. As a quick fix, you can either manually add the following missing logging permission to the CRRHourlyMaintRole or add it to the CloudFormation template and then update the stack. 

"logs:CreateLogGroup",
 "logs:CreateLogStream",
 "logs:PutLogEvents"

**Comment by p-doyle** [comment]
Looks like this was fixed in a commit a few months ago.   Thanks!
